name: lint
on: push
permissions:
  contents: read
jobs:
  build:
    strategy:
      matrix:
        go-version: [1.19.x, 1.20.x]
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
      with:
        egress-policy: audit

    - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
    - name: Set up Go
      uses: actions/setup-go@7b8cf10d4e4a01d4992d18a89f4d7dc5a3e6d6f4 # v4.3.0
      with:
        go-version: ${{ matrix.go-version }}
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v ./...
  lint:
    strategy:
      matrix:
        go-version: [1.19.x, 1.20.x]
        os: [macos-latest, ubuntu-latest]
    name: lint
    runs-on: ${{ matrix.os }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
        with:
          egress-policy: audit

      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
      - name: golangci-lint
        uses: golangci/golangci-lint-action@3a919529898de77ec3da873e3063ca4b10e7f5cc # v3.7.0
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.53
